### ISSUE TITLE
[DEV] - Add tests to the images

### ISSUE THREAD

**Issue by trallard** [nebari-dev/nebari-docker-images#2]
A CI/CD workflow should test the images after the build and before pushing.

## Tasks

- [ ] Identify and add common tests (for all images)
- [ ] Identify and add any image specific tests
- [ ] Add step to GH action workflow

**Comment by trallard** [comment]
https://github.com/jupyter/docker-stacks/tree/main/tests

**Comment by trallard** [comment]
Also explore - https://github.com/NVIDIA/container-canary

**Comment by viniciusdc** [comment]
Work in progress finished setting up the workflow ecosystem, currently:
- Writing the docker wrapper to interact with the built images and execute the pytest scripts
- Writing specialized tests for each image
- Will need to rebase to sync with main

**Comment by viniciusdc** [comment]
I am mostly following the workflow structure defined on [jupyter/docker-stacks](https://github.com/jupyter/docker-stacks), right now I've set the workflow ecosystem and was working on setting [pytest-docker](https://github.com/avast/pytest-docker) to run the pytest scripts in the image containers.
